name: Gold Price Daily Scraper

on:
  schedule:
    - cron: '0 4 * * *'  # Runs daily at 4 AM UTC (you can adjust)
  workflow_dispatch:     # Allows manual trigger from GitHub

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # or your preferred version

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run the bot
        run: |
          python gold_price_bot.py

      - name: Commit updated CSV
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add gold_prices.csv
          git commit -m "Update gold prices [bot]" || echo "No changes to commit"
          git push
